### ISSUE TITLE
eww+logos: Is it possible to read the web using logos?

### ISSUE THREAD

**Issue by Ypot** [protesilaos/logos#4]
Could logos be used in webpages? (eww)

Some things work, other ones don't. 
Main issue seems to be that the paragraphs look unfilled. 
Font type doesn't change, but in EWW it can be changed manually using `F`

No logos:
![imagen](https://user-images.githubusercontent.com/30699014/185791051-695dd8e5-0647-4e25-b4aa-bbe1ad199d88.png)

Logos:
![imagen](https://user-images.githubusercontent.com/30699014/185791075-dad8195e-bd53-4a1d-b4c4-d7804c99b592.png)

Logos + toggle font:
![imagen](https://user-images.githubusercontent.com/30699014/185791133-ef44a1bc-4409-423f-b563-6b4d686892b9.png)

**Comment by protesilaos** [comment]
Hello @Ypot!

The weird paragraph filling is because `shr-max-width` is set to a fairly high value.  Try this instead:

```elisp
(setq shr-max-width fill-column)
```

For the fonts, it defaults to `variable-pitch` by default, but it can be made to look like the rest of Emacs with this:

```elisp
(setq shr-use-fonts nil)
```

These should make EWW buffers the same as all others.

**Comment by Ypot** [comment]
It got better!

Thank you, for discovering to me the shr variables :-)
I have set the `olivetti-body-width` (enabled with logos) to the `shr-max-width`.
And now it looks like **logos** :-)


Suggestion when logos is enabled in an eww buffer:
- Set font (`eww-toggle-fonts`) according to `logos-variable-pitch`
- Set `shr-max-width` to `olivetti-body-width` if `logos-olivetti` is on
- Eval function `eww-readable` (if user selects it in the **logos** customization menu).

**Comment by protesilaos** [comment]
> Suggestion when logos is enabled in an eww buffer: [...]

Yes, we need to handle this directly.  I will look into it.  About `eww-readable`, shouldn't that be left to the user?

**Comment by Ypot** [comment]
> Yes, we need to handle this directly. I will look into it. About `eww-readable`, shouldn't that be left to the user?

Yes, in the logos customization menu user could choose it :-)

**Comment by protesilaos** [comment]
I am looking into it.  Apparently it is not a mode/toggle so we shouldn't touch it.  The reason is that we cannot cleanly restore the previous state when `logos-focus-mode` is disabled.

**Comment by protesilaos** [comment]
Changing the `shr-max-width` is not as straightforward because the web page needs to be reloaded again.  I am looking into it, but any tweak will go in the manual for users to add to their configuration, not in logos.el.

**Comment by Ypot** [comment]
What would be the problem if web page reloads when enabling and disabling logos-mode?

**Comment by protesilaos** [comment]
> What would be the problem if the web page reloads when enabling and disabling logos-mode?

Depending on the page's contents, this is not instant.  If it has a few images, for example, there is a delay.  This is not how `olivetti-mode` works in other contexts, so a page reload is surprising.

In terms of implementation, we have to deal with moving parts:

+ `shr-width`, `shr-max-width`, and `shr-use-fonts` from shr.el;
+ `olivetti-body-width`, `olivetti-minimum-body-width` from olivetti.el;
+ `logos-variable-pitch` from logos.el.

These are user options.  We cannot anticipate how the user prefers to do things.  For example, I use this:

```elisp
(setq olivetti-body-width 0.7)
```

Whereas its default value is `nil`.

So if we try to force a specific value, we are likely to get bug reports about it when it conflicts/undoes the user's configurations.

This is why any tweaks have to be done by the user, because then they get the exact behaviour they want/design.  I think making EWW look like the rest of Emacs is how the default should be: https://protesilaos.com/emacs/logos#h:2b598775-8a3d-4728-a7ce-edc05d90fdb9
