### ISSUE TITLE
Set cursor color

### ISSUE THREAD

**Issue by Ypot** [protesilaos/logos#8]
I want to set cursor color in logos-focus-mode, but after disabling logos-focus-mode, the color doesn't change back to the "default" color. 
If I restart emacs, it works as intended, and it changes to the "default" color.

```emacs lisp
(defun my-logos-no-blink-cursor ()
  "Fixed cursor to avoid distractions reading"
  (setq blink-cursor-blinks 1)
  (set-cursor-color "#969696"))
(add-hook 'logos-focus-mode-extra-functions #'my-logos-no-blink-cursor)
```

**Comment by protesilaos** [comment]
For this you need to use the `logos-focus-mode-hook`.  Like this:

```elisp
(defun my-logos-no-blink-cursor ()
  "Fixed cursor to avoid distractions reading"
  (if logos-focus-mode
      (progn
        (setq blink-cursor-blinks 1)
        (set-cursor-color "#969696"))
    ;; If `logos-focus-mode' is off, use those...
    (setq blink-cursor-blinks 10)
    (set-cursor-color "#ff0000")))

(add-hook 'logos-focus-mode-hook #'my-logos-no-blink-cursor)
```

**Comment by Ypot** [comment]
It works!

Could it be possible to know why mine didn't work?
- I see that you use "if" because after disabling logos-focus-mode the modification doesn't change back. Why?
- And I see that instead of `logos-focus-mode-extra-functions` you use `logos-focus-mode-hook`. Why?

If those questions exceed the scope of this thread or forum, no need to answer :-)

Thanks!

**Comment by protesilaos** [comment]
> It works!

Very well!

> Could it be possible to know why mine didn't work?
> - I see that you use "if" because after disabling logos-focus-mode the modification doesn't change back. Why?
> - And I see that instead of `logos-focus-mode-extra-functions` you use `logos-focus-mode-hook`. Why?

The reason you need `logos-focus-mode-hook` is because any function bound there is called both when the mode is enabled and disabled.  Whereas `logos-focus-mode-extra-functions` is only for the enabled state.  It is like that because the functions that are meant to work with it must be like those mentioned in the doc string of `logos-focus-mode-extra-functions`: they have to use functions like `logos--set`, which take care to disable the value they define.

**Comment by protesilaos** [comment]
Maybe this can be simplified in the future.  Will look into it.
